[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "human-pose-tracking"
version = "0.1.0"
requires-python = ">=3.8,<3.12"
keywords = []

dependencies = [
  "mediapipe==0.10.9",
  "numpy",
  "opencv-python>4.6",
  "requests>=2.31,<3",
  "rerun-sdk",
]


[[tool.hatch.envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11"]

