[package]
name = "dna"
version = "0.21.0-rc.2"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
rerun = { path = "../../../crates/top/rerun" }

itertools = "0.13"
rand = "0.8"
