[package]
name = "rerun-loader-rust-file"
version = "0.23.3-rc.2"
edition = "2021"
rust-version = "1.84"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
rerun = { path = "../../../crates/top/rerun" }

anyhow = "1.0"
argh = "0.1"
