[package]
name = "re_datafusion"
authors.workspace = true
description = "Datafusion bindings on top of Rerun"
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true


[features]
default = []

[dependencies]
re_chunk = { workspace = true, features = ["serde"] }
re_chunk_store.workspace = true
re_format.workspace = true
re_log.workspace = true
re_log_types.workspace = true

anyhow.workspace = true
ahash.workspace = true
datafusion.workspace = true
document-features.workspace = true
tokio.workspace = true
arrow = "52.1.0"
async-trait = "0.1.81"

[dev-dependencies]
re_types.workspace = true

[lib]
bench = false

[[example]]
name = "datafusion"
path = "examples/datafusion.rs"
