[package]
name = "template"
version = "0.23.0-rc.3"
edition = "2021"
rust-version = "1.84"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
rerun = { path = "../../../crates/top/rerun" }
