[package]
name = "re_math"
authors.workspace = true
description = "3D math utilities built on glam"
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true


[features]
default = ["serde"]

serde = ["dep:serde"]

[dependencies]
glam.workspace = true

serde = { workspace = true, optional = true, features = ["derive"] }
