#:schema ./schema.json
# Examples listed in this manifest will appear on our website.
# This has no effect whatsoever on whether they appear in the app itself.
#
# To add examples to the app itself, use the `channel` attribute in the example's readme's frontmatter.
# See <https://github.com/rerun-io/rerun/tree/main/examples#adding-a-new-example> for more information.

[categories.use-cases]
order = 1
title = "Examples with Real Data"
prelude = """
The following examples illustrate using the Rerun logging SDK with potential real-world (if toy) use cases.
They all require additional data to be downloaded, so an internet connection is needed at least once.
Each example downloads it's own data, so no additional steps are needed.
For the simplest possible examples showing how to use each api,
check out [Types](/docs/reference/types).

You can try these examples live at <https://app.rerun.io/>.
"""
examples = [
  "arkit_scenes",
  "controlnet",
  "depth_guided_stable_diffusion",
  "detect_and_track_objects",
  "dicom_mri",
  "face_tracking",
  "human_pose_tracking",
  "gesture_detection",
  "lidar",
  "live_camera_edge_detection",
  "live_depth_sensor",
  "llm_embedding_ner",
  "nuscenes",
  "objectron",
  "open_photogrammetry_format",
  "raw_mesh",
  "rgbd",
  "ros_node",
  "segment_anything_model",
  "signed_distance_fields",
  "structure_from_motion",
  "vrs",
  "arflow",
  "differentiable_blocks_world",
  "limap",
  "mcc",
  "shape_pointe",
  "simplerecon",
  "slahmr",
  "tapir",
  "widebaseline",
]

[categories.feature-use]
order = 2
title = "Examples with Artificial Data"
prelude = """
The following examples serve to illustrate various uses of the Rerun logging SDK.
They should not require any additional data downloads, and should run offline.
For the simplest possible examples showing how to use each api,
check out [Types](/docs/reference/types).
"""
examples = [
  "minimal",
  "clock",
  "eigen_opencv",
  "multithreading",
  "multiprocessing",
  "plots",
]
