#:schema ./schema.json
# Examples listed in this manifest will appear on our website.
# This has no effect whatsoever on whether they appear in the app itself.
#
# To add examples to the app itself, use the `channel` attribute in the example's readme's frontmatter.
# See <https://github.com/rerun-io/rerun/tree/main/examples#adding-a-new-example> for more information.

[categories.spatial-computing]
order = 1
title = "Spatial computing and XR"
prelude = """
TODO
"""
examples = [
  "arkit_scenes",
  "objectron",
  "vrs",
  "arflow",
  "widebaseline",
  "simplerecon",
  "slahmr",
  "limap",
]

[categories.robotics]
order = 2
title = "Robotics"
prelude = """
TODO
"""
examples = ["nuscenes", "ros_node"]

[categories.generative-vision]
order = 3
title = "Generative computer vision"
prelude = """
TODO
"""
examples = [
  "controlnet",
  "depth_guided_stable_diffusion",
  "mcc",
  "shape_pointe",
]

[categories.video-image]
order = 4
title = "Video and image understanding"
prelude = """
TODO
"""
examples = [
  "detect_and_track_objects",
  "face_tracking",
  "human_pose_tracking",
  "gesture_detection",
  "segment_anything_model",
  "tapir",
  "live_camera_edge_detection",
]

[categories.3d-reconstruction]
order = 4
title = "3D reconstruction and modelling"
prelude = """
TODO
"""
examples = [
  "signed_distance_fields",
  "structure_from_motion",
  "differentiable_blocks_world",
  "open_photogrammetry_format",
]

examples_other = ["live_depth_sensor", "llm_embedding_ner", "raw_mesh"]

[categories.sensor-output]
order = 2
title = "Sensor output"
prelude = """
TODO
"""
examples = ["rgbd", "lidar"]

[categories.integrations]
order = 2
title = "Integrations"
prelude = """
TODO
"""
examples = ["vrs", "ros_node", "eigen_opencv", "dicom_mri"]

[categories.feature-showcase]
order = 2
title = "Feature showcase"
prelude = """
TODO
"""
examples = ["minimal", "clock", "multithreading", "multiprocessing", "plots"]
