[package]
name = "re_test_viewport"
description = "A viewport used for tests"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
re_test_context.workspace = true
# re_chunk.workspace = true
# re_chunk_store.workspace = true
# re_entity_db.workspace = true
# re_global_context.workspace = true
# re_grpc_client.workspace = true
# re_log_types.workspace = true
# re_tracing.workspace = true
# re_types.workspace = true
# re_types_core.workspace = true
re_ui.workspace = true
re_viewer_context.workspace = true
re_viewport_blueprint.workspace = true
re_viewport.workspace = true

# External dependencies
ahash.workspace = true
# anyhow.workspace = true
egui.workspace = true
# egui_kittest.workspace = true
# once_cell.workspace = true
# parking_lot.workspace = true
