
[package]
name = "re_workspace_hack"
version = "0.1.0"
edition = "2021"
description = "workspace-hack package, managed by hakari"
publish = false                                           # We do NOT want to publish this!

[lints]
workspace = true

[dependencies]
# This file was originally created with `cargo hakari generate`, then shortened down to what you see.
# To update it you can either edit it manually, or run `cargo hakari generate` and then remove most of what you end up with
# See https://crates.io/crates/hakari and https://crates.io/crates/cargo-hakari for more
### BEGIN HAKARI SECTION
datafusion = { version = "47" }
datafusion-common = { version = "47", default-features = false, features = ["parquet", "recursive_protection"] }
datafusion-datasource = { version = "47", default-features = false, features = ["compression", "parquet"] }
datafusion-expr = { version = "47", default-features = false, features = ["recursive_protection"] }
datafusion-functions = { version = "47", features = ["crypto_expressions"] }
datafusion-optimizer = { version = "47", default-features = false, features = ["recursive_protection"] }
datafusion-physical-optimizer = { version = "47", default-features = false, features = ["recursive_protection"] }
datafusion-sql = { version = "47", features = ["recursive_protection"] }
### END HAKARI SECTION
