[package]
name = "minimal_serve"
version = "0.23.4-alpha.1"
edition = "2021"
rust-version = "1.84"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
rerun = { path = "../../../crates/top/rerun", features = ["web_viewer"] }
